// This file is part of sketch-hct-plugin. It is subject to the license terms in the LICENSE file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/sketch-hct-plugin/master/LICENSE. No part of sketch-hct-plugin, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the LICENSE file.
// Copyright © 2024 The developers of sketch-hct-plugin. See the LICENSE file in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/sketch-hct-plugin/master/LICENSE.

import {UppercaseHexadecimalSixDigitRedGreenBlueColorString} from "./UppercaseHexadecimalSixDigitRedGreenBlueColorString";

export interface MaterialDesignScheme
{
	primary: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	surfaceTint: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onPrimary: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	primaryContainer: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onPrimaryContainer: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	secondary: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onSecondary: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	secondaryContainer: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onSecondaryContainer: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	tertiary: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onTertiary: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	tertiaryContainer: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onTertiaryContainer: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	error: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onError: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	errorContainer: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onErrorContainer: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	background: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onBackground: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	surface: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onSurface: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	surfaceVariant: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onSurfaceVariant: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	outline: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	outlineVariant: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	shadow: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	scrim: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	inverseSurface: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	inverseOnSurface: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	inversePrimary: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	primaryFixed: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onPrimaryFixed: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	primaryFixedDim: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onPrimaryFixedVariant: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	secondaryFixed: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onSecondaryFixed: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	secondaryFixedDim: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onSecondaryFixedVariant: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	tertiaryFixed: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onTertiaryFixed: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	tertiaryFixedDim: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	onTertiaryFixedVariant: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	surfaceDim: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	surfaceBright: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	surfaceContainerLowest: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	surfaceContainerLow: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	surfaceContainer: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	surfaceContainerHigh: UppercaseHexadecimalSixDigitRedGreenBlueColorString
	surfaceContainerHighest: UppercaseHexadecimalSixDigitRedGreenBlueColorString
}
