// This file is part of sketch-hct-plugin. It is subject to the license terms in the LICENSE file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/sketch-hct-plugin/master/LICENSE. No part of sketch-hct-plugin, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the LICENSE file.
// Copyright © 2024 The developers of sketch-hct-plugin. See the LICENSE file in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/sketch-hct-plugin/master/LICENSE.

export enum SwatchName
{
	PrimaryPaletteKeyColor = "1 Primary/Key",
	SecondaryPaletteKeyColor = "2 Secondary/Key",
	TertiaryPaletteKeyColor = "3 Tertiary/Key",
	NeutralPaletteKeyColor = "4 Neutral/Key",
	NeutralVariantPaletteKeyColor = "4 Neutral/Key/Variant",
	ErrorPaletteKeyColor = "6 Error/Key",
	Background = "5 Surface/Background",
	OnBackground = "5 Surface/Background/On",
	Surface = "5 Surface/2",
	SurfaceDim = "5 Surface/1 Dim",
	SurfaceBright = "5 Surface/3 Bright",
	SurfaceContainerLowest = "5 Surface/Container/1 Lowest",
	SurfaceContainerLow = "5 Surface/Container/2 Low",
	SurfaceContainer = "5 Surface/Container/3",
	SurfaceContainerHigh = "5 Surface/Container/4 High",
	SurfaceContainerHighest = "5 Surface/Container/5 Highest",
	OnSurface = "5 Surface/On",
	SurfaceVariant = "5 Surface/Variant",
	OnSurfaceVariant = "5 Surface/On/Variant",
	InverseSurface = "5 Surface/Inverse",
	InverseOnSurface = "5 Surface/Inverse/On",
	Outline = "4 Neutral/Outline",
	OutlineVariant = "4 Neutral/Outline/Variant",
	Shadow = "4 Neutral/Shadow",
	Scrim = "4 Neutral/Scrim",
	SurfaceTint = "1 Primary/Surface Tint",
	Primary = "1 Primary",
	OnPrimary = "1 Primary/On",
	PrimaryContainer = "1 Primary/Container",
	OnPrimaryContainer = "1 Primary/Container/On",
	InversePrimary = "1 Primary/Inverse",
	Secondary = "2 Secondary",
	OnSecondary = "2 Secondary/On",
	SecondaryContainer = "2 Secondary/Container",
	OnSecondaryContainer = "2 Secondary/Container/On",
	Tertiary = "3 Tertiary",
	OnTertiary = "3 Tertiary/On",
	TertiaryContainer = "3 Tertiary/Container",
	OnTertiaryContainer = "3 Tertiary/Container/On",
	Error = "6 Error",
	OnError = "6 Error/On",
	ErrorContainer = "6 Error/Container",
	OnErrorContainer = "6 Error/Container/On",
	PrimaryFixed = "1 Primary/Fixed",
	PrimaryFixedDim = "1 Primary/Fixed/Dim",
	OnPrimaryFixed = "1 Primary/Fixed/On",
	OnPrimaryFixedVariant = "1 Primary/Fixed/On/Variant",
	SecondaryFixed = "2 Secondary/Fixed",
	SecondaryFixedDim = "2 Secondary/Fixed/Dim",
	OnSecondaryFixed = "2 Secondary/Fixed/On",
	OnSecondaryFixedVariant = "2 Secondary/Fixed/Variant",
	TertiaryFixed = "3 Tertiary/Fixed",
	TertiaryFixedDim = "3 Tertiary/Fixed/Dim",
	OnTertiaryFixed = "3 Tertiary/Fixed/On",
	OnTertiaryFixedVariant = "3 Tertiary/Fixed/On/Variant",
}
