#!/usr/bin/env sh
# This file is part of sketch-hct-plugin. It is subject to the license terms in the LICENSE file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/sketch-hct-plugin/master/LICENSE. No part of sketch-hct-plugin, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the LICENSE file.
# Copyright © 2024 The developers of sketch-hct-plugin. See the LICENSE file in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/sketch-hct-plugin/master/LICENSE.

set -e
set -f
set -u

_program_path_find()
{
	if [ "${0%/*}" = "$0" ]; then

		# We've been invoked by the interpreter as, say, bash program
		if [ -r "$0" ]; then
			pwd -P
		# Clutching at straws; probably run via a download, anonymous script, etc, weird execve, etc
		else
			printf '\n'
		fi

	else

		# We've been invoked with a relative or absolute path (also when invoked via PATH in a shell)

		_program_path_find_parentPath()
		{
			parentPath="${scriptPath%/*}"
			if [ -z "$parentPath" ]; then
				parentPath='/'
			fi
			cd "$parentPath" 1>/dev/null
		}

		# pdksh / mksh have problems with unsetting a variable that was never set...
		if [ "${CDPATH+set}" = 'set' ]; then
			unset CDPATH
		fi

		if command -v realpath 1>/dev/null 2>/dev/null; then
			(
				scriptPath="$(realpath "$0")"

				_program_path_find_parentPath
				pwd -P
			)
		elif command -v readlink 1>/dev/null 2>/dev/null; then
			(
				local -r recursionDepth=0
				_program_path_resolve_symlinks_recursively()
				{
					local -r unresolvedPath="$1"

					recursionDepth=$((recursionDepth + 1))

					if [ $recursionDepth -gt 10 ]; then
						printf '%s\n' 'Recursion to depths greater than 10 is not allowed when resolving links.'
						return 1
					fi

					local -r potentialLinkDestination="$(readlink -- "$unresolvedPath")"

					if [ -z "$potentialLinkDestination" ]; then
						scriptPath="$unresolvedPath"
						return 0
					fi
					local -r linkDestination="$potentialLinkDestination"
					local -r parentFolderPath="${unresolvedPath%/*}"

					if [ "$parentFolderPath" = "$unresolvedPath" ]; then
						_program_path_resolve_symlinks_recursively "$linkDestination"
					else
						case "$linkDestination" in

							/*)
								_program_path_resolve_symlinks_recursively "$linkDestination"
							;;

							*)
								_program_path_resolve_symlinks_recursively "$parentFolderPath"/"$linkDestination"
							;;

						esac
					fi
				}

				scriptPath="$0"
				_program_path_resolve_symlinks_recursively "$scriptPath"

				_program_path_find_parentPath
				pwd -P
			)
		else
			# This approach will fail in corner cases where the script itself is a symlink in a path not parallel with the concrete script
			(
				scriptPath="$0"

				_program_path_find_parentPath
				pwd -P
			)
		fi

	fi
}

main_bun()
{
	local -r local_bunfig_file_path="$HOME"/.bunfig.toml
	if is_readable_file "$local_bunfig_file_path"; then
		exit_error "Remove $local_bunfig_file_path; this file overrides global configuration in an undesirable way"
	fi

	local -r bun_home_folder_path="$root_folder_path"/lib/bun
	local -r dot_bun_folder_path="$bun_home_folder_path"/.bun
	local -r install_dot_bun_folder_path="$dot_bun_folder_path"/install

	#unset NODE_TLS_REJECT_UNAUTHORIZED
	export BUN_CONFIG_VERBOSE_FETCH=curl
	export BUN_RUNTIME_TRANSPILER_CACHE_PATH="$TMPDIR"/bun-transpiler-cache
	export BUN_CONFIG_MAX_HTTP_REQUESTS=256
	export BUN_CONFIG_NO_CLEAR_TERMINAL_ON_RELOAD=true
	export DO_NOT_TRACK=1
	export NO_COLOR=1
	export FORCE_COLOR=0
	export XDG_CONFIG_HOME="$root_folder_path"/libexec/bun

	# Undocumented; override .bunfig.toml which does not support environment variables and for which globalCacheDir is ignored!
	export BUN_INSTALL_GLOBAL_DIR="$install_dot_bun_folder_path"/global
	export BUN_INSTALL_BIN="$root_folder_path"/bin
	export BUN_INSTALL_CACHE_DIR="$install_dot_bun_folder_path"/cache

	bun_run true "$@"
}

main()
{
	cd "$(_program_path_find)" 1>/dev/null 2>/dev/null
		local -r program_folder_path="$(pwd)"
	cd -  1>/dev/null 2>/dev/null

	cd "$program_folder_path"/../.. 1>/dev/null 2>/dev/null
    	local -r root_folder_path="$(pwd)"
	cd -  1>/dev/null 2>/dev/null

	local -r functions_folder_path="$root_folder_path"/lib/posix-shell/functions

	. "$functions_folder_path"/essential.sh
	. "$functions_folder_path"/clean-environment.sh
	. "$functions_folder_path"/bun.sh
	clean_environment ''

	main_bun "$@"
}

main "$@"
